### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by satyaloka93** [khromov/ai-digest#1]
I am trying to use your repo to make a MD file of downloaded Github repo: https://github.com/stanfordnlp/dspy. However, when I try to run this after installing, I get the following error:

```shell
/root/.npm/_npx/764439b5c8abeeaf/node_modules/commander/lib/command.js:396
    enableOrNameAndArgs = enableOrNameAndArgs ?? 'help [command]';
                                               ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/root/.npm/_npx/764439b5c8abeeaf/node_modules/commander/index.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
Command used:
```shell
npx ai-digest -i ./dspy-2.4.12 -o dspy_2_4_12.md --whitespace-removal --show-output-files
```
Would love to use this, as it seems very helpful to bundle code for upload to LLMs, any guidance on solving would be appreciated.

**Comment by khromov** [comment]
@satyaloka93 Hi! Which version of Node are you using? (`node --version`)

I tried the above repo with Node 18 and that did work. Anything older than that will unfortunately not be supported.

I will make a small note that since the repo contains a special AI token you might get a warning about `Error: The text contains a special token that is not allowed: <|endoftext|>`, but the Markdown file will still be generated.

**Comment by satyaloka93** [comment]
I get version 12.22.9 with that command. I am using wsl2, so perhaps the apt repo doesn't have the right version.

**Comment by khromov** [comment]
Please install nvm by running their install script:
https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating

Then in a new console, type `nvm i 22`. From now on you should have an up to date version of Node. If you want to go back you can manually install Node 12 using nvm as well.

**Comment by satyaloka93** [comment]
Ok, upgrading via nvm script worked, thanks for the tip!
